<?php
// api/gamification/get-quiz-certification.php
header('Content-Type: application/json');
session_start();

// 20 certification questions covering all disaster types
$questions = [
    // EARTHQUAKE
    ['id'=>1001,'category'=>'earthquake','question'=>'What should you do FIRST when an earthquake starts?','option_a'=>'Run outside immediately','option_b'=>'Drop, Cover, and Hold On','option_c'=>'Call emergency services','option_d'=>'Stand in a doorway','correct_answer'=>'B','explanation'=>'Drop, Cover, and Hold On is the safest action. Running outside risks injury from falling debris. Doorways are not safer than other parts of the building.','points'=>10],
    ['id'=>1002,'category'=>'earthquake','question'=>'After an earthquake, what is the greatest secondary hazard?','option_a'=>'Aftershocks','option_b'=>'Tsunami (if near coast)','option_c'=>'Fire from broken gas lines','option_d'=>'All of the above','correct_answer'=>'D','explanation'=>'All are serious secondary hazards. Aftershocks can cause further damage, tsunamis may follow coastal earthquakes, and broken gas lines can cause fires.','points'=>10],
    ['id'=>1003,'category'=>'earthquake','question'=>'Where is the SAFEST place to be during an earthquake indoors?','option_a'=>'Near windows','option_b'=>'Under a sturdy table or desk','option_c'=>'In a hallway','option_d'=>'Near exterior walls','correct_answer'=>'B','explanation'=>'Under a sturdy table or desk protects you from falling objects. Windows, hallways, and exterior walls are more dangerous.','points'=>10],

    // TYPHOON
    ['id'=>1004,'category'=>'typhoon','question'=>'What does a Signal No. 4 typhoon warning mean in the Philippines?','option_a'=>'Winds of 60 kph expected in 36 hours','option_b'=>'Winds of 185 kph or more expected within 12 hours','option_c'=>'Typhoon is 500km away','option_d'=>'Light rains only','correct_answer'=>'B','explanation'=>'Signal No. 4 is the highest warning level, meaning very destructive typhoon-force winds of 185 kph or more are expected within 12 hours.','points'=>10],
    ['id'=>1005,'category'=>'typhoon','question'=>'What should you prepare in your emergency kit before a typhoon?','option_a'=>'Only food and water','option_b'=>'Food, water, flashlight, first aid, important documents','option_c'=>'Just a flashlight','option_d'=>'Nothing, wait for the storm to pass','correct_answer'=>'B','explanation'=>'A complete emergency kit includes food and water for 3 days, flashlight, first aid kit, important documents, medicine, and extra clothes.','points'=>10],
    ['id'=>1006,'category'=>'typhoon','question'=>'During a typhoon, if you are caught outdoors, you should:','option_a'=>'Find shelter under a tree','option_b'=>'Stay near rivers to monitor water levels','option_c'=>'Find a sturdy building and stay away from windows','option_d'=>'Drive to higher ground','correct_answer'=>'C','explanation'=>'Find a sturdy building immediately. Trees can fall, rivers can flood rapidly, and driving during a typhoon is extremely dangerous.','points'=>10],

    // FIRE
    ['id'=>1007,'category'=>'fire','question'=>'What is the correct order to use a fire extinguisher?','option_a'=>'Pull, Aim, Squeeze, Sweep (PASS)','option_b'=>'Squeeze, Aim, Pull, Sweep','option_c'=>'Aim, Pull, Sweep, Squeeze','option_d'=>'Sweep, Pull, Aim, Squeeze','correct_answer'=>'A','explanation'=>'PASS: Pull the pin, Aim at the base of the fire, Squeeze the handle, Sweep side to side. Always aim at the base, not the flames.','points'=>10],
    ['id'=>1008,'category'=>'fire','question'=>'If you are trapped in a burning building, what should you do?','option_a'=>'Open all windows to let smoke out','option_b'=>'Use the elevator to escape faster','option_c'=>'Seal door gaps with cloth and signal from a window','option_d'=>'Hide under the bed','correct_answer'=>'C','explanation'=>'Seal door gaps to slow smoke entry, stay low, and signal rescuers from a window. Never use elevators during a fire.','points'=>10],
    ['id'=>1009,'category'=>'fire','question'=>'What should you do when you hear a fire alarm?','option_a'=>'Wait to confirm it is real before evacuating','option_b'=>'Use the elevator for faster exit','option_c'=>'Evacuate immediately using the nearest fire exit','option_d'=>'Gather all your belongings first','correct_answer'=>'C','explanation'=>'Always treat fire alarms as real and evacuate immediately. Use stairs, not elevators. Leave belongings behind.','points'=>10],

    // FLOOD
    ['id'=>1010,'category'=>'flood','question'=>'How much moving water can knock a person off their feet?','option_a'=>'3 feet deep','option_b'=>'6 inches of fast-moving water','option_c'=>'Only 2 feet deep','option_d'=>'Water cannot knock a person over','correct_answer'=>'B','explanation'=>'Only 6 inches of fast-moving water can knock an adult off their feet. Never try to walk through flood waters.','points'=>10],
    ['id'=>1011,'category'=>'flood','question'=>'What should you do if your vehicle stalls in floodwater?','option_a'=>'Stay in the vehicle and call for help','option_b'=>'Abandon the vehicle and move to higher ground','option_c'=>'Try to restart the engine repeatedly','option_d'=>'Wait for the water to go down','correct_answer'=>'B','explanation'=>'Abandon the vehicle immediately and move to higher ground. Vehicles can be swept away rapidly. Your life is more important than the vehicle.','points'=>10],
    ['id'=>1012,'category'=>'flood','question'=>'What color warning means EXTREME FLOODING is imminent in the Philippines?','option_a'=>'Yellow','option_b'=>'Orange','option_c'=>'Red','option_d'=>'Purple','correct_answer'=>'C','explanation'=>'Red rainfall warning means intense to torrential rainfall is occurring and flooding is imminent or already happening. Immediate action is needed.','points'=>10],

    // LANDSLIDE
    ['id'=>1013,'category'=>'landslide','question'=>'Which of these is a WARNING SIGN of an impending landslide?','option_a'=>'Clear sunny weather','option_b'=>'Cracks appearing in the ground or walls','option_c'=>'Birds flying away','option_d'=>'Temperature drops','correct_answer'=>'B','explanation'=>'Cracks in the ground, walls, or roads are serious warning signs of landslide. Others include tilting trees, unusual sounds, and springs appearing in new areas.','points'=>10],
    ['id'=>1014,'category'=>'landslide','question'=>'During heavy rainfall in a mountainous area, you should:','option_a'=>'Stay near rivers to monitor flooding','option_b'=>'Move away from steep slopes and unstable areas','option_c'=>'Climb to the top of a hill','option_d'=>'Dig trenches around your house','correct_answer'=>'B','explanation'=>'Move away from steep slopes, riverbanks, and unstable areas during heavy rain. These are prime landslide zones.','points'=>10],
    ['id'=>1015,'category'=>'landslide','question'=>'What is the PRIMARY cause of landslides in Baguio City?','option_a'=>'Earthquakes only','option_b'=>'Heavy and prolonged rainfall','option_c'=>'Strong winds','option_d'=>'Extreme heat','correct_answer'=>'B','explanation'=>'Heavy and prolonged rainfall is the primary trigger for landslides in Baguio and the Cordillera region, saturating slopes and causing soil instability.','points'=>10],

    // GENERAL PREPAREDNESS
    ['id'=>1016,'category'=>'general','question'=>'What is the recommended minimum water supply per person per day in an emergency?','option_a'=>'Half a liter','option_b'=>'1 liter','option_c'=>'At least 2 liters (for drinking and sanitation)','option_d'=>'5 liters','correct_answer'=>'C','explanation'=>'FEMA and WHO recommend at least 2 liters of water per person per day for drinking and basic sanitation during emergencies.','points'=>10],
    ['id'=>1017,'category'=>'general','question'=>'What does the acronym "CERT" stand for in disaster preparedness?','option_a'=>'Community Emergency Response Team','option_b'=>'Civil Emergency Rescue Team','option_c'=>'Crisis Emergency Relief Task Force','option_d'=>'Central Emergency Response Training','correct_answer'=>'A','explanation'=>'CERT stands for Community Emergency Response Team — trained volunteers who assist with disaster response in their communities.','points'=>10],
    ['id'=>1018,'category'=>'general','question'=>'What is a "Go Bag" in emergency preparedness?','option_a'=>'A bag you send to evacuees','option_b'=>'A pre-packed bag with essentials ready for quick evacuation','option_c'=>'A government-issued emergency kit','option_d'=>'A bag for collecting donations','correct_answer'=>'B','explanation'=>'A Go Bag (or Bug-Out Bag) is a pre-packed bag with essential supplies — food, water, documents, medicine — ready for immediate evacuation.','points'=>10],
    ['id'=>1019,'category'=>'general','question'=>'In the Philippines, which agency is the PRIMARY coordinator for disaster response?','option_a'=>'Philippine National Police (PNP)','option_b'=>'Armed Forces of the Philippines (AFP)','option_c'=>'National Disaster Risk Reduction and Management Council (NDRRMC)','option_d'=>'Department of Health (DOH)','correct_answer'=>'C','explanation'=>'The NDRRMC is the primary government body for disaster risk reduction and management in the Philippines, coordinating all disaster response efforts.','points'=>10],
    ['id'=>1020,'category'=>'general','question'=>'What is the universal emergency hotline number in the Philippines?','option_a'=>'112','option_b'=>'911','option_c'=>'117','option_d'=>'8888','correct_answer'=>'B','explanation'=>'911 is the emergency hotline in the Philippines for police, fire, and medical emergencies. It was launched nationwide in 2016.','points'=>10],
];

echo json_encode([
    'success' => true,
    'questions' => $questions,
    'total' => count($questions)
]);
