<?php
// api/gamification/get-quiz.php
header('Content-Type: application/json');
session_start();

$category = isset($_GET['category']) ? $_GET['category'] : 'general';
$limit = isset($_GET['limit']) ? (int)$_GET['limit'] : 5;

$all_questions = [
    'earthquake' => [
        ['id'=>101,'question'=>'What should you do FIRST when an earthquake starts?','option_a'=>'Run outside immediately','option_b'=>'Drop, Cover, and Hold On','option_c'=>'Call emergency services','option_d'=>'Stand in a doorway','correct_answer'=>'B','explanation'=>'Drop, Cover, and Hold On protects you from falling debris. Running outside risks injury. Doorways offer no special protection.','points'=>10],
        ['id'=>102,'question'=>'After shaking stops, what should you check for first?','option_a'=>'Your phone','option_b'=>'Injuries and gas leaks','option_c'=>'Damage to furniture','option_d'=>'Your neighbors','correct_answer'=>'B','explanation'=>'Check yourself and others for injuries first, then check for gas leaks which can cause fires or explosions.','points'=>10],
        ['id'=>103,'question'=>'Where is the SAFEST place during an earthquake indoors?','option_a'=>'Near windows','option_b'=>'Under a sturdy table or desk','option_c'=>'In a hallway','option_d'=>'Near exterior walls','correct_answer'=>'B','explanation'=>'Under a sturdy table protects you from falling objects. Windows and exterior walls are more dangerous.','points'=>10],
        ['id'=>104,'question'=>'What should you do if you are in bed during an earthquake?','option_a'=>'Run to the door','option_b'=>'Stay in bed, cover your head with a pillow','option_c'=>'Go under the bed','option_d'=>'Jump out the window','correct_answer'=>'B','explanation'=>'Stay in bed and cover your head with a pillow. The mattress provides some protection and moving risks injury from falling objects.','points'=>10],
        ['id'=>105,'question'=>'How long should you wait outside after an earthquake before re-entering a building?','option_a'=>'5 minutes','option_b'=>'Until authorities say it is safe','option_c'=>'1 hour','option_d'=>'Until aftershocks stop completely','correct_answer'=>'B','explanation'=>'Always wait for official clearance before re-entering. Aftershocks can cause already-weakened structures to collapse.','points'=>10],
    ],
    'typhoon' => [
        ['id'=>201,'question'=>'What does Signal No. 1 mean in Philippine typhoon warnings?','option_a'=>'Typhoon has made landfall','option_b'=>'Winds of 30-60 kph expected within 36 hours','option_c'=>'Evacuate immediately','option_d'=>'Typhoon is 1000km away','correct_answer'=>'B','explanation'=>'Signal No. 1 means winds of 30-60 kph are expected within 36 hours. Schools may be suspended but it is the lowest warning level.','points'=>10],
        ['id'=>202,'question'=>'What should you do BEFORE a typhoon arrives?','option_a'=>'Wait and see how strong it gets','option_b'=>'Prepare emergency kit, secure loose items, know your evacuation route','option_c'=>'Board up windows only','option_d'=>'Nothing if you live in a concrete house','correct_answer'=>'B','explanation'=>'Preparation is key: prepare an emergency kit, secure loose outdoor items that can become projectiles, and know your evacuation route in advance.','points'=>10],
        ['id'=>203,'question'=>'Is it safe to go outside during the eye of a typhoon?','option_a'=>'Yes, the eye is calm and safe','option_b'=>'No, the other half of the typhoon is still coming','option_c'=>'Yes, but only for 30 minutes','option_d'=>'Yes, the typhoon is over','correct_answer'=>'B','explanation'=>'Never go outside during the eye. It is temporarily calm but the back half of the typhoon (often stronger) is still approaching.','points'=>10],
        ['id'=>204,'question'=>'What is a storm surge?','option_a'=>'Heavy rainfall from a typhoon','option_b'=>'An abnormal rise in sea level caused by a typhoon\'s winds','option_c'=>'Flash flooding from rivers','option_d'=>'Strong winds near the typhoon center','correct_answer'=>'B','explanation'=>'A storm surge is a dangerous rise of water pushed ashore by typhoon winds. It can be more deadly than the wind itself.','points'=>10],
        ['id'=>205,'question'=>'After a typhoon, what should you avoid?','option_a'=>'Eating canned food','option_b'=>'Walking through floodwaters which may be contaminated','option_c'=>'Staying indoors','option_d'=>'Using flashlights','correct_answer'=>'B','explanation'=>'Floodwaters are contaminated with sewage, chemicals, and debris. Avoid contact and never walk or drive through them.','points'=>10],
    ],
    'fire' => [
        ['id'=>301,'question'=>'What does PASS stand for when using a fire extinguisher?','option_a'=>'Pull, Aim, Squeeze, Sweep','option_b'=>'Push, Activate, Spray, Stop','option_c'=>'Pull, Activate, Squirt, Swing','option_d'=>'Press, Aim, Spray, Sweep','correct_answer'=>'A','explanation'=>'PASS: Pull the pin, Aim at the BASE of the fire, Squeeze the handle, Sweep side to side. Always aim at the base not the flames.','points'=>10],
        ['id'=>302,'question'=>'If your clothes catch fire, what should you do?','option_a'=>'Run to find water','option_b'=>'Stop, Drop, and Roll','option_c'=>'Take off clothes immediately','option_d'=>'Fan the flames away','correct_answer'=>'B','explanation'=>'Stop, Drop, and Roll smothers the flames by cutting off oxygen. Running fans the fire and makes it worse.','points'=>10],
        ['id'=>303,'question'=>'When escaping a fire, you should stay:','option_a'=>'Standing upright to move faster','option_b'=>'Low to the ground where air is cleaner','option_c'=>'Near windows','option_d'=>'In the center of hallways','correct_answer'=>'B','explanation'=>'Smoke rises. Stay low where the air is cleaner and cooler. Smoke inhalation is the leading cause of fire deaths.','points'=>10],
        ['id'=>304,'question'=>'Before opening a door during a fire, you should:','option_a'=>'Open it quickly and run through','option_b'=>'Feel the door and knob for heat first','option_c'=>'Break it down','option_d'=>'Knock on it','correct_answer'=>'B','explanation'=>'Feel the door with the back of your hand. If it is hot, fire is on the other side. Find another exit or shelter in place.','points'=>10],
        ['id'=>305,'question'=>'What is the leading cause of home fires?','option_a'=>'Electrical problems','option_b'=>'Cooking','option_c'=>'Smoking','option_d'=>'Candles','correct_answer'=>'B','explanation'=>'Cooking is the leading cause of home fires. Never leave cooking unattended and keep flammable materials away from the stove.','points'=>10],
    ],
    'flood' => [
        ['id'=>401,'question'=>'How much moving water can sweep away a car?','option_a'=>'At least 5 feet','option_b'=>'Just 2 feet of rushing water','option_c'=>'Only if water is 10 feet deep','option_d'=>'Cars cannot be swept by water','correct_answer'=>'B','explanation'=>'Just 2 feet of rushing water can carry away most vehicles. Never drive through flooded roads.','points'=>10],
        ['id'=>402,'question'=>'What should you do if told to evacuate due to flooding?','option_a'=>'Wait to see if flooding actually happens','option_b'=>'Evacuate immediately via designated routes','option_c'=>'Move to the second floor instead','option_d'=>'Secure your valuables first, then leave','correct_answer'=>'B','explanation'=>'Follow evacuation orders immediately. Floods can rise very quickly. Designated routes are chosen to avoid flood-prone roads.','points'=>10],
        ['id'=>403,'question'=>'After a flood, tap water should be:','option_a'=>'Safe to drink right away','option_b'=>'Boiled or treated before drinking until cleared safe','option_c'=>'Only used for bathing','option_d'=>'Avoided for 1 year','correct_answer'=>'B','explanation'=>'Floodwaters can contaminate the water supply. Boil water or use bottled water until authorities declare the water supply safe.','points'=>10],
        ['id'=>404,'question'=>'What causes flash floods?','option_a'=>'Only ocean storms','option_b'=>'Sudden heavy rainfall, often with little warning','option_c'=>'Slow rise of river levels','option_d'=>'Melting ice caps','correct_answer'=>'B','explanation'=>'Flash floods are caused by sudden, intense rainfall. They can occur within minutes and with very little warning, making them extremely dangerous.','points'=>10],
        ['id'=>405,'question'=>'During a flood warning, you should move to:','option_a'=>'The basement','option_b'=>'Higher ground or upper floors','option_c'=>'Near the river to monitor it','option_d'=>'Your neighbor\'s house','correct_answer'=>'B','explanation'=>'Move to higher ground or upper floors of a sturdy building. Never go to basements or ground floors during flooding.','points'=>10],
    ],
    'landslide' => [
        ['id'=>501,'question'=>'Which warning sign indicates a landslide may be imminent?','option_a'=>'Increased bird activity','option_b'=>'Cracks appearing in the ground or on walls','option_c'=>'Decrease in temperature','option_d'=>'Strong wind gusts','correct_answer'=>'B','explanation'=>'Ground cracks, tilting trees, new springs appearing, and unusual sounds (cracking, rumbling) are all warning signs of impending landslides.','points'=>10],
        ['id'=>502,'question'=>'When should you evacuate to avoid landslides?','option_a'=>'Only when you see the landslide starting','option_b'=>'During prolonged heavy rainfall in mountainous areas','option_c'=>'Only during earthquakes','option_d'=>'Only during typhoons','correct_answer'=>'B','explanation'=>'Evacuate proactively during prolonged heavy rain in mountain areas. Do not wait until you see movement — by then it may be too late.','points'=>10],
        ['id'=>503,'question'=>'Which areas are MOST at risk for landslides?','option_a'=>'Flat coastal areas','option_b'=>'Steep slopes, deforested hills, and areas near rivers','option_c'=>'Urban city centers','option_d'=>'Desert areas','correct_answer'=>'B','explanation'=>'Steep slopes, deforested areas (trees anchor soil), and riverbanks are highest risk. Baguio City\'s hillside barangays are especially vulnerable.','points'=>10],
        ['id'=>504,'question'=>'What should you do if caught in a landslide?','option_a'=>'Run downhill away from the slide','option_b'=>'Move sideways out of the path and seek shelter behind a sturdy object','option_c'=>'Stay still and cover yourself','option_d'=>'Run back uphill','correct_answer'=>'B','explanation'=>'Move quickly sideways out of the landslide path. Get behind a sturdy structure or boulder if possible. Never run downhill in the path of the slide.','points'=>10],
        ['id'=>505,'question'=>'What human activity MOST increases landslide risk?','option_a'=>'Planting trees','option_b'=>'Deforestation and illegal cutting of trees','option_c'=>'Building concrete roads','option_d'=>'Farming on flat land','correct_answer'=>'B','explanation'=>'Deforestation removes tree roots that bind soil together. This dramatically increases landslide risk, especially on steep slopes.','points'=>10],
    ],
    'general' => [
        ['id'=>601,'question'=>'How many days of supplies should an emergency kit contain?','option_a'=>'1 day','option_b'=>'At least 3 days (72 hours)','option_c'=>'1 week minimum','option_d'=>'1 month','correct_answer'=>'B','explanation'=>'Emergency management agencies recommend at least 72 hours (3 days) of supplies including water, food, and medicine in your emergency kit.','points'=>10],
        ['id'=>602,'question'=>'What is the Philippine emergency hotline number?','option_a'=>'117','option_b'=>'911','option_c'=>'8888','option_d'=>'112','correct_answer'=>'B','explanation'=>'911 is the national emergency hotline for police, fire, and medical emergencies in the Philippines.','points'=>10],
        ['id'=>603,'question'=>'What does NDRRMC stand for?','option_a'=>'National Disaster Risk Reduction and Management Council','option_b'=>'National Department of Rescue, Relief, and Mitigation Committee','option_c'=>'National Disaster Recovery and Relief Management Center','option_d'=>'National Department of Risk Reduction Measures Committee','correct_answer'=>'A','explanation'=>'NDRRMC is the National Disaster Risk Reduction and Management Council — the primary government body coordinating disaster response in the Philippines.','points'=>10],
        ['id'=>604,'question'=>'What should be in a basic first aid kit?','option_a'=>'Only bandages','option_b'=>'Bandages, antiseptic, pain reliever, scissors, gloves, and first aid manual','option_c'=>'Just medicine','option_d'=>'Food and water only','correct_answer'=>'B','explanation'=>'A complete first aid kit includes bandages, antiseptic wipes, pain reliever, scissors, disposable gloves, and a first aid manual at minimum.','points'=>10],
        ['id'=>605,'question'=>'What is the purpose of a family evacuation plan?','option_a'=>'Just a government requirement','option_b'=>'To ensure all family members know what to do and where to go in an emergency','option_c'=>'Only needed for businesses','option_d'=>'Not necessary if you have a car','correct_answer'=>'B','explanation'=>'A family evacuation plan ensures everyone knows the meeting point, exit routes, and emergency contacts so you can act quickly without confusion.','points'=>10],
    ],
];

$questions = isset($all_questions[$category]) ? $all_questions[$category] : $all_questions['general'];

// Shuffle and limit
shuffle($questions);
$questions = array_slice($questions, 0, $limit);

// Re-index IDs so they are unique per session
echo json_encode([
    'success' => true,
    'category' => $category,
    'questions' => $questions,
    'total' => count($questions)
]);
